# Generated by Django 3.2.8 on 2022-11-17 07:26

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BluePrint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('blueprint_details', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'BluePrint',
            },
        ),
        migrations.CreateModel(
            name='BluePrintComments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'blueprintComments',
            },
        ),
        migrations.CreateModel(
            name='BluePrintCommentsReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'BlueprintCommentsReply',
            },
        ),
        migrations.CreateModel(
            name='BluePrintNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('comment', 'Comment'), ('reply', 'Reply'), ('Product_create', 'product_create'), ('Product_update', 'product_update')], max_length=100)),
                ('action_status', models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Useen')], default='unseen', max_length=100)),
                ('higlight_status', models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Useen')], default='unseen', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BluePrintShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='sent', max_length=100)),
                ('message', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'BluePrintShare',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBluePrint',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('blueprint_details', models.JSONField(default=list, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical blue print',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('subline_text', models.CharField(max_length=100, null=True)),
                ('process_item_id', models.IntegerField()),
                ('data', models.JSONField(null=True)),
                ('blue_print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processdata', to='blueprint.blueprint')),
            ],
            options={
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
