# Generated by Django 3.2.8 on 2022-11-17 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('momentum_report', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotification',
            name='action_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_action_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='momentum_report.taskcomments'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='org_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_org_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='momentum_report.taskcommentsreply'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='momentum_report.report'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='momentum_report.task'),
        ),
        migrations.AddField(
            model_name='taskcommentsreply',
            name='task_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='momentum_report.taskcomments'),
        ),
        migrations.AddField(
            model_name='taskcommentsreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reply_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentum_report.task'),
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='reports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentum_report.report'),
        ),
        migrations.AddField(
            model_name='reportshare',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportshare',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentum_report.report'),
        ),
        migrations.AddField(
            model_name='reportshare',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report_pdf',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentum_report.report'),
        ),
        migrations.AddField(
            model_name='report',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentum_report.projectfromworkzone'),
        ),
        migrations.AddField(
            model_name='projectlogo',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentum_report.projectfromworkzone'),
        ),
        migrations.AddField(
            model_name='projectfromworkzone',
            name='organization_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='historicaltaskcommentsreply',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskcommentsreply',
            name='task_comment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='momentum_report.taskcomments'),
        ),
        migrations.AddField(
            model_name='historicaltaskcommentsreply',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskcomments',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskcomments',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='momentum_report.task'),
        ),
        migrations.AddField(
            model_name='historicaltaskcomments',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
