# Generated by Django 3.2.8 on 2022-11-17 07:26

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPatterComments',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('comments', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=list, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical patter comments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPatterCommentsReply',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('comments', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=list, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical patter comments reply',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPattern',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.JSONField(default=list, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical pattern',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PatterComments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'PatterComments',
            },
        ),
        migrations.CreateModel(
            name='PatterCommentsReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'PatterCommentsReply',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'Patterns',
            },
        ),
        migrations.CreateModel(
            name='PatternFont',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('generic', models.CharField(max_length=50, null=True)),
                ('upload_flag', models.BooleanField(default=False)),
                ('data_file_path', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('font_type', models.CharField(choices=[('file', 'file'), ('url', 'url'), ('text', 'text')], max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'PatternFont',
            },
        ),
        migrations.CreateModel(
            name='PatternNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('comment', 'Comment'), ('reply', 'Reply'), ('Product_create', 'product_create'), ('Product_update', 'product_update')], max_length=100)),
                ('action_status', models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Useen')], default='unseen', max_length=100)),
                ('higlight_status', models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Useen')], default='unseen', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatternSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('has_sub_section', models.BooleanField(default=False)),
                ('section_icon', models.JSONField(default=dict, null=True)),
                ('section_type', models.CharField(choices=[('list', 'list'), ('image', 'image'), ('text', 'text')], max_length=20)),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'PatternSections',
            },
        ),
        migrations.CreateModel(
            name='PatternSectionCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('data_list', models.JSONField(default=list, null=True)),
                ('data_text', models.TextField(null=True)),
                ('data_image', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'PatternSectionCollections',
            },
        ),
        migrations.CreateModel(
            name='PatternSubSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'PatternSubSections',
            },
        ),
        migrations.CreateModel(
            name='PatterShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='sent', max_length=100)),
                ('message', models.CharField(max_length=1000, null=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
            ],
            options={
                'verbose_name_plural': 'PatterShare',
            },
        ),
    ]
