"""
Django settings for roadmap project.
Generated by 'django-admin startproject' using Django 2.2.3.
For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
import pdfkit


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%+!!u)%yhzcxn^jsa(js&jkt#3=qq!o!8a4=-yhid#p-ihwflu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    # '127.0.0.1',
    # 'roadmap.logicplum.com',
    # 'roadmap-api.logicplum.com',
    # '52.176.164.243'
    '*'
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'users',
    'organizations',
    'projects',
    'simple_history',
    'patterns',
    'context',
    'blueprint',
    'momentum_report',
    'ApiServices',
]

MIDDLEWARE = [
    'ApiServices.middleware.apidata_middleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'users.middleware.UserActivityMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'quiver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['quiver/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quiver.wsgi.application'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'quiver_dev',
        'USER': 'quiverdbbuser',
        'PASSWORD': 'bph72E@mmWJsFeP',
        'HOST': 'quiverdb.postgres.database.azure.com',
        'PORT': 5432,
        # 'OPTIONS': {'sslmode': 'require'},
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'lpquiver_dev',
#         'USER': 'rm_admin',
#         'PASSWORD': 'Lp$mysql#2021!rm1',
#         'HOST': 'localhost',
#         'PORT': 5432,
#         # 'OPTIONS': {'sslmode': 'require'},
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
#         'LOCATION': 'C:\\WINDOWS\\Temp\\polaris_local_cache' if sys.platform == "win32" else '/var/tmp/polaris_local_cache',
#         'TIMEOUT': 600,
#         'OPTIONS': {
#             'MAX_ENTRIES': 1000
#         }
#     }
# }

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # 'DEFAULT_PAGINATION_CLASS':['rest_framework.pagination.LimitOffsetPagination',]
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.LimitOffsetPagination'
}

# Django-REST-Framework simplejwt configurations
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=300),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Quiver',
    'DESCRIPTION': 'APIs for Quiver',
    'VERSION': '1.0.0',
    'SERVE_AUTHENTICATION': None,
    # OTHER SETTINGS
    'DISABLE_ERRORS_AND_WARNINGS': False,
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        },
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

# Email server configurations
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'notification@logicplum.com'
DEFAULT_FROM_EMAIL = 'notification@logicplum.com'
SERVER_EMAIL = 'notification@logicplum.com'
EMAIL_HOST_PASSWORD = 'Lp$Nt!Plus#2021'

CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:4200",
    "http://localhost:4200",
    "http://alignmentchain-dev-api.logicplum.com",
    'http://alignmentchain-dev.logicplum.com'

]
CSRF_TRUSTED_ORIGINS = [
    '127.0.0.1:4200', 'localhost:4200', 'http://alignmentchain-dev-api.logicplum.com', 'http://alignment-chain-dev.logicplum.com'
]

CORS_URLS_REGEX = r'^/api/v1/.*$'


CORS_ORIGIN_WHITELIST = [
    'http://localhost:4200',
    'http://alignmentchain-dev.logicplum.com','http://alignmentchain-dev-api.logicplum.com',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
    'access-control-max-age',
]

CORS_ALLOW_METHODS = [
'DELETE',
'GET',
'OPTIONS',
'PATCH',
'POST',
'PUT',
]
 
APPEND_SLASH = False

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_DOMAIN = "alignmentchain-dev-api.logicplum.com"

# SECURE_SSL_REDIRECT = False
 

# SITE_ORIGIN is required to send emails with links
SITE_ORIGIN = 'http://alignmentchain-dev.logicplum.com/login?key='

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'US/Pacific'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#Notification time settings

CENTRAL_TIME_ZONE = 'US/Central'
NOTIFY_YEAR = 2021
NOTIFY_MONTH = 8
NOTIFY_DAY = 16
NOTIFY_HOUR = 19
NOTIFY_MINUTE = 0
NOTIFY_SECOND = 0
NOTIFY_M_SECOND = 0

FEEDBACK_EMAIL = ["message@logicplum.com","feba.mathew@logicplum.com"]
USER_URL="http://alignmentchain-dev.logicplum.com/login?canvas_id="
# For sentry implementation
#----------------------------#
sentry_sdk.init(
    dsn="https://2733d90b12bf4eabbba231c46a040ccf@o276122.ingest.sentry.io/6315747",
    integrations=[DjangoIntegration()],
 
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,
 
    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)


SITE_URL = "http://alignmentchain-dev.logicplum.com/"


ROOT_URL="http://alignmentchain-dev-api.logicplum.com"

CONFIGPDF = pdfkit.configuration(wkhtmltopdf = "/usr/local/bin/wkhtmltopdf") 
# CONFIGPDF = pdfkit.configuration(wkhtmltopdf ="C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe")

MEDIA_ROOTPDF=str(os.path.dirname(os.path.realpath(__name__))).replace("\\","/")+"/quiver/media/Reports/"

MEDIA_URLPDF=ROOT_URL+"/media/Reports/"

MEDIA_LOGOIMG="http://alignmentchain-dev-api.logicplum.com/media/"