# Generated by Django 3.2.8 on 2022-11-17 07:26

from django.db import migrations, models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('write', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Collaborator',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProjects',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archive', 'Archive')], default='active', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProjectsOrganizationMapping',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical projects organization mapping',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRoadMapFeatures',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=500)),
                ('reach', models.FloatField(default=0.0)),
                ('impact', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('effort', models.FloatField(default=0.0)),
                ('score', models.FloatField(default=0.0)),
                ('rice_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archive', 'Archive'), ('complete', 'Complete')], default='active', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('image', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical road map features',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRoadMaps',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical road maps',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archive', 'Archive')], default='active', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectsOrganizationMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProjectsOrganizationMapping',
            },
        ),
        migrations.CreateModel(
            name='RoadMapComments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'RoadMapComments',
            },
        ),
        migrations.CreateModel(
            name='RoadMapCommentsReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'RoadMapCommentsReply',
            },
        ),
        migrations.CreateModel(
            name='RoadMapFeatures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('reach', models.FloatField(default=0.0)),
                ('impact', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('effort', models.FloatField(default=0.0)),
                ('score', models.FloatField(default=0.0)),
                ('rice_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archive', 'Archive'), ('complete', 'Complete')], default='active', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('image', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'RoadMapFeatures',
            },
        ),
        migrations.CreateModel(
            name='RoadMapNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('comment', 'Comment'), ('reply', 'Reply'), ('Product_create', 'product_create'), ('Product_update', 'product_update'), ('feature_create', 'Feature_create'), ('feature_update', 'Feature_update')], max_length=100)),
                ('action_status', models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Useen')], default='unseen', max_length=100)),
                ('higlight_status', models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Useen')], default='unseen', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoadMaps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'RoadMaps',
            },
        ),
        migrations.CreateModel(
            name='RoadMapShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='sent', max_length=100)),
                ('message', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'RoadMapShare',
            },
        ),
    ]
