# Generated by Django 3.2.8 on 2022-11-17 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ApiServices', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinotification',
            name='action_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_action_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apinotification',
            name='apiname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiServices.apidetails'),
        ),
        migrations.AddField(
            model_name='apinotification',
            name='org_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_org_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apinotification',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AddField(
            model_name='apidetails',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='apidetails',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AddField(
            model_name='apicalldetails',
            name='apiname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiServices.apidetails'),
        ),
        migrations.AddField(
            model_name='apicalldetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
