# Generated by Django 3.2.8 on 2022-11-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidetails',
            name='api_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
