# Generated by Django 3.2.8 on 2022-11-17 07:26

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(max_length=50)),
                ('user_list', models.JSONField(default=dict, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Canvas',
            },
        ),
        migrations.CreateModel(
            name='CanvasComments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'CanvasComments',
            },
        ),
        migrations.CreateModel(
            name='CanvasCommentsReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'CanvasCommentsReply',
            },
        ),
        migrations.CreateModel(
            name='CanvasMembers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'CanvasMembers',
            },
        ),
        migrations.CreateModel(
            name='CanvasNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('colour', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'CanvasNotes',
            },
        ),
        migrations.CreateModel(
            name='CanvasNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('comment', 'Comment'), ('reply', 'Reply'), ('Product_create', 'product_create'), ('Product_update', 'product_update')], max_length=100)),
                ('action_status', models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Useen')], default='unseen', max_length=100)),
                ('higlight_status', models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Useen')], default='unseen', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanvasShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(default='sent', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'CanvasShare',
            },
        ),
        migrations.CreateModel(
            name='CanvasTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(default=dict, null=True)),
            ],
            options={
                'verbose_name_plural': 'CanvasTask',
            },
        ),
        migrations.CreateModel(
            name='CanvasType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'CanvasType',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('canvas_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_type', to='context.canvastype')),
            ],
            options={
                'verbose_name_plural': 'Priority',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCanvasMembers',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('count', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('canvas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='context.canvas')),
            ],
            options={
                'verbose_name': 'historical canvas members',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
